### ISSUE TITLE
trailing slash doesn't resolve to pages 

### ISSUE THREAD

**Issue by starpause** [CODAME/codame-website#15]
http://codame.com/pages/media-kit/

doesn't resolve to 

http://codame.com/pages/media-kit

**Comment by jpalmieri** [comment]
@jouncealimb it looks like you were able to resolve this in https://github.com/CODAME/codame-website/commit/04dc1ffe134ed44918d276f6138111a41735e51f, yeah?

**Comment by gridwalk** [comment]
Deployed to production. Thanks Dani and Joe!
