### ISSUE TITLE
Copy/move volunteer deck

### ISSUE THREAD

**Issue by endquote** [CODAME/codame-website#25]
There's a volunteer opportunities deck embedded on this page:
http://codame.com/pages/join-us

But if I'm sending out the link to the join us form to get volunteers, I'm sending them to here:
http://codame.com/pages/call-for-volunteers

And that deck isn't there.

Could we replace the photo on the call for volunteers page with the deck? And maybe we remove it from the join us page?

/cc @starpause

**Comment by BrunoFonzi** [comment]
Not a project issues, those can be applied using the content management tools provided.
